insert into public.internships (
  name,
  institution,
  location,
  summary,
  ideal_candidate,
  opportunity_type,
  deadline,
  website,
  comments
)
values
  ('Johns Hopkins SOM', 'Johns Hopkins SOM', 'MD', '', null, null, null, 'https://www.hopkinsmedicine.org/som/pathway/sip', 'Dr. Bennett has overseen a student from one of these programs and has many local connections including a great local church.  Good to apply to if you are the first in your family to attend college.'),
  ('Uni of Maryland', 'Uni of Maryland', 'MD', '', null, null, null, 'https://www.umms.org/umgccc/healthcare-professionals/crcera/undergraduate/translational-cancer-research-intern-program', 'Dr. Bennett has worked with a student from this program, knows the director and a Sattler student has been in the program.'),
  ('Summer Programs for Pre-Health Students', 'Penn State', 'PA', '', null, null, null, 'Summer Programs for Pre-Health Students', 'Clinically oriented'),
  ('Clinical Observation and Career Shadowing - Penn State College of Medicine', '', 'PA', '', null, null, null, 'Clinical Observation and Career Shadowing - Penn State College of Medicine', 'Clinically oriented Lists diverse programs some of which are listed below'),
  ('Undergraduate Research Internships - Penn State College of Medicine', '', 'PA', '', null, null, null, 'Undergraduate Research Internships - Penn State College of Medicine', 'Research oriented Note the list of programs (like below) under this link'),
  ('Summer Undergraduate Research Internship Program (SURIP) - Penn State College of Medicine', '', 'PA', '', null, null, null, 'Summer Undergraduate Research Internship Program (SURIP) - Penn State College of Medicine', 'research oriented, no pre-med students Note there is a Kingdom outreach to international students at Penn State main campus if you are interested in evangelism.'),
  ('Short-Term Educational Program to Unlock Potential (STEP-UP) - Penn State College of Medicine', '', 'PA', '', null, null, null, 'Short-Term Educational Program to Unlock Potential (STEP-UP) - Penn State College of Medicine', 'research oriented'),
  ('LaSalle Uni', 'LaSalle Uni', 'PA', '', null, null, null, 'https://www.lasalle.edu/pre-health/summer-opportunities/', ''),
  ('SPARC - DF/HCC', 'Dana Farber/Harvard', 'MA', '', null, null, null, 'SPARC - DF/HCC', 'Dr. Bennett has overseen a student from this program, and Sattler student(s) have obtained this internship.  Good to apply to if you are the first in your family to attend college.'),
  ('CURE Overview - DF/HCC', '', 'MA', '', null, null, null, 'CURE Overview - DF/HCC', ''),
  ('Uni of IA', 'Uni of IA', 'IA', '', null, null, null, 'https://medicine.uiowa.edu/research/student-opportunities/undergraduate-opportunities', ''),
  ('NSF Research Experiences for Undergraduates', 'NSF', 'varied', '', null, null, null, 'NSF Research Experiences for Undergraduates', 'Dr. Bennett got this internship as an undergrad.'),
  ('Clinic for Special Children', 'Clinic for Special Children', 'PA, OH, IN, WI, KY', '', null, null, null, 'https://clinicforspecialchildren.org/contact/fellowships-internships/', 'A Sattler student has obtained this internship. Other clinics in the Plain Community Health Consortium may also have internships.'),
  ('Eurofins Careers - Job Categories', 'Eurofins/Lancaster Labs', 'Global/PA', '', null, null, null, 'Eurofins Careers - Job Categories', ''),
  ('Sunnybrook', 'Sunnybrook', 'ON', '', null, null, null, 'https://sunnybrook.ca/research/content/?page=sri-ed-summ-uni', ''),
  ('Undergraduate Summer Research Program at The Lunenfeld-Tanenbaum Research Institute', 'Lunenfeld Tanenbaum Research Institute:', 'ON', '', null, null, null, 'Undergraduate Summer Research Program at The Lunenfeld-Tanenbaum Research Institute', ''),
  ('Atlantis', 'Atlantis', 'varied', '', null, null, null, 'https://info.joinatlantis.com/keepmeupdated-shadowing?utm_source=google&utm_medium=cpc&utm_campaign=829+%7C+Atlantis+%7C+Performance+Max&utm_term=&utm_campaign=&utm_source=adwords&utm_medium=ppc&hsa_ver=3&hsa_acc=9427622304&hsa_mt=&hsa_src=x&hsa_cam=16083733611&hsa_grp=&hsa_tgt=&hsa_kw=&hsa_ad=&hsa_net=adwords&gclid=CjwKCAiA4KaRBhBdEiwAZi1zzjCZdOHkg3RNjNXV6b8AlvwYk2jMeksLMZvla8mimo5k3wvU4-DzVxoCAtcQAvD_BwE', 'Medical Shadowing Program'),
  ('SickKids', 'SickKids', 'Toronto, ON', '', null, null, null, 'https://www.sickkids.ca/en/research/research-training-centre/summer-research-program/', ''),
  ('EFCC Summer Undergraduate Research Fellowship (SURF)', 'Uni of MO', 'MO', '', null, null, null, 'EFCC Summer Undergraduate Research Fellowship (SURF)', 'Cancer biology specifically'),
  ('NIH', 'NIH', 'MD, etc.', '', null, null, null, 'https://www.training.nih.gov/research-training/pb/sip/', 'esp look at C-SOAR'),
  ('Broad Summer Research Program (BSRP)', 'Broad Institute', 'MA', '', null, null, null, 'Broad Summer Research Program (BSRP)', ''),
  ('BU', 'BU', 'MA', '', null, null, null, 'https://www.bu.edu/surf/about/', ''),
  ('UMass Chan Med School', 'UMass Chan Med School', 'MA', '', null, null, null, 'https://www.umassmed.edu/gsbs/outreach-programs', ''),
  ('UPenn', 'UPenn', 'PA', '', null, null, null, 'https://www.ucspinfo.org/about.html', ''),
  ('Thomas Jefferson Univerisity', 'Thomas Jefferson Univerisity', 'PA', '', null, null, null, 'https://www.jefferson.edu/academics/colleges-schools-institutes/life-sciences/other-opportunities/summer-program.html', ''),
  ('Drexel School of Med', 'Drexel School of Med', 'PA', '', null, null, null, 'https://drexel.edu/medicine/research/student-research/summer-undergraduate-research-fellowship/', ''),
  ('Geisinger Health', 'Geisinger Health', 'PA', '', null, null, null, 'https://www.geisinger.edu/gchs/research/participate-in-research/research-internships', ''),
  ('Lehigh Valley Health Network', 'Lehigh Valley Health Network', 'PA', '', null, null, null, 'https://www.lvhn.org/education/college-programs/research-scholar-program', ''),
  ('University of Pittsburgh', 'University of Pittsburgh', 'PA', '', null, null, null, 'https://www.cnup.pitt.edu/phd-program-training/summer-undergraduate-research-program', ''),
  ('MHIF (Minneapolis)', 'MHIF (Minneapolis)', 'MN', '', null, null, null, 'https://www.mplsheart.org/clinical-research-internship-program', ''),
  ('Siteman Cancer Center (MO)', 'Siteman Cancer Center (MO)', 'MO', '', null, null, null, 'https://siteman.wustl.edu/research/training/opportunities/graduate/programs/summer/', ''),
  ('Cornell University', 'Cornell University', 'NY', '', null, null, null, 'https://cals.cornell.edu/molecular-biology-genetics/academics/undergraduate/summer-research-experience-undergraduates-reu-program', ''),
  ('MSK Cancer Center', 'MSK Cancer Center', 'NY', '', null, null, null, 'https://www.mskcc.org/hcp-education-training/medical-students/summer-fellowship', ''),
  ('CSHL (Long Island)', 'CSHL (Long Island)', 'NY', '', null, null, null, 'https://www.cshl.edu/education/undergraduate-research-program/#applying', ''),
  ('Cincinatti School of Med', 'Cincinatti School of Med', 'OH', '', null, null, null, 'https://www.cincinnatichildrens.org/education/research/surf/program', ''),
  ('OHSU (Oregon)', 'OHSU (Oregon)', 'OR', '', null, null, null, 'https://www.ohsu.edu/school-of-medicine/cell-developmental-and-cancer-biology/biomedical-bioinformatics-research', ''),
  ('Georgetown University', 'Georgetown University', 'DC', '', null, null, null, 'https://som.georgetown.edu/diversityequityandinclusion/guarches/archesoverview/', ''),
  ('Columbia University', 'Columbia University', 'NY', '', null, null, null, 'https://www.publichealth.columbia.edu/research/programs/biostatistics-epidemiology-summer-training/about', ''),
  ('Pritzker School of Med', 'Pritzker School of Med', 'IL', '', null, null, null, 'https://pritzker.uchicago.edu/resources/summer-pathway-programs', ''),
  ('Vanderbuilt University', 'Vanderbuilt University', 'TN', '', null, null, null, 'https://medschool.vanderbilt.edu/vssa/undergraduate-clinical-research-internship-program/', ''),
  ('Mayo Clinic', 'Mayo Clinic', 'MN', '', null, null, null, 'https://college.mayo.edu/academics/biomedical-research-training/summer-undergraduate-research-fellowship-surf/', ''),
  ('Med College of Wisconsin', 'Med College of Wisconsin', 'WI', '', null, null, null, 'https://www.mcw.edu/education/graduate-school/prospective-students/summer-program-for-undergraduate-research', ''),
  ('Med U of S. Carolina', 'Med U of S. Carolina', 'SC', '', null, null, null, 'https://gradstudies.musc.edu/programs/summer-program/undergraduate', ''),
  ('Weill Cornell Med School', 'Weill Cornell Med School', 'NY', '', null, null, null, 'https://medicaleducation.weill.cornell.edu/medical-education/premedical-programs/travelers-summer-research-fellowship-program', ''),
  ('Summer Student Pre-Med & Research Program | hartfordhealthcare.org | Hartford HealthCare | CT', 'Harford Hospital', 'CT', '', null, null, null, 'Summer Student Pre-Med & Research Program | hartfordhealthcare.org | Hartford HealthCare | CT', ''),
  ('Keck School of Medicine', 'Keck School of Medicine', 'CA', '', null, null, null, 'https://keck2.usc.edu/bridging-the-gaps-program/about-bridging-the-gaps', ''),
  ('Overlook health (NJ)', 'Overlook health (NJ)', 'NJ', '', null, null, null, 'https://www.atlantichealth.org/professionals-medical-education/internship-programs/overlook-summer-internship-program.html', ''),
  ('Yale', 'Yale', 'CT', '', null, null, null, 'https://physics-engineering-biology.yale.edu/nsf-reu-site', ''),
  ('UCSF (San Francisco)', 'UCSF (San Francisco)', 'CA', '', null, null, null, 'https://graduate.ucsf.edu/academics/srtp#Program-Features-and-Benefits', ''),
  ('Icahn School of Medicine', 'Icahn School of Medicine', 'NY', '', null, null, null, 'https://icahn.mssm.edu/education/non-degree/surp4us', ''),
  ('UC San Diego', 'UC San Diego', 'CA', '', null, null, null, 'https://medschool.ucsd.edu/education/mstp/surf/Pages/features.aspx', ''),
  ('The Top 40 Pre-med Summer Internships', 'Varied', 'varied', '', null, null, null, 'The Top 40 Pre-med Summer Internships', ''),
  ('CalTech', 'CalTech', 'CA', '', null, null, null, 'https://sfp.caltech.edu/undergraduate-research/programs/wavefellows', 'Dr. Kuruvilla connections'),
  ('Indiana University SOM', 'Indiana University SOM', 'IN', '', null, null, null, 'https://medicine.iu.edu/research-centers/pediatrics/education/internships', ''),
  ('Indiana University Cancer Center', 'Indiana University Cancer Center', 'IN', '', null, null, null, 'https://cancer.iu.edu/education/summer/index.html', ''),
  ('Summer Undergraduate Research Program | Harvard Medical School', 'BCMP Scholars SURP', 'MA', '', null, null, null, 'Summer Undergraduate Research Program | Harvard Medical School', 'Highly competitive; Dr. Bennett has some connections'),
  ('Big Ten Alliance', 'SROP', '', '', null, null, null, 'Big Ten Alliance', 'Big Ten Academic Alliance SROP -')
on conflict (name, institution) do update
set
  location = excluded.location,
  summary = excluded.summary,
  ideal_candidate = excluded.ideal_candidate,
  opportunity_type = excluded.opportunity_type,
  deadline = excluded.deadline,
  website = excluded.website,
  comments = excluded.comments,
  updated_at = now();
